spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redline
    username: redline
    password: redline

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.redline: DEBUG
    org.hibernate.SQL: DEBUG
